spring.application.name=bookstore

# ===============================
# DATABASE
# ===============================

spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test
spring.datasource.username=3TQ4cXVRxZdCSHK.root
spring.datasource.password=b5pP76w11vJYQaWS

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Session
server.servlet.session.timeout = 30m

# upload size
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB